version: '3.8'

services:
  app:
    build: .
    container_name: vaimo-recommendation-system
    ports:
      - "8000:8000"
    volumes:
      # Mount data directory for development (optional)
      - ./data:/app/data:ro
      # Mount app directory for development with hot reload (optional)
      - ./app:/app/app:ro
    environment:
      - PYTHONPATH=/app
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/', timeout=10)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - recommendation-network

  # Optional: Add a reverse proxy for production
  # nginx:
  #   image: nginx:alpine
  #   container_name: vaimo-nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - app
  #   networks:
  #     - recommendation-network

networks:
  recommendation-network:
    driver: bridge

# Optional: Add volumes for data persistence
# volumes:
#   app_data:
#     driver: local 